export const TRACK_CATALOG = {
    circuit: { name: "Classic Circuit" },
    sunlitTemple: { name: "Sunlit Temple" },
    royalPlateau: { name: "Royal Plateau" },
    mistwoodSerpent: { name: "Mistwood Serpent" },
    harborParkLoop: { name: "Harbor Park" },
    jadeSpiralCircuit: { name: "Jade Spiral" },
    cedarRidgeCircuit: { name: "Cedar Ridge" },
    twinRise: { name: "Twin Rise" },
    sakuraWeave: { name: "Sakura Weave" },
    kettleRun: { name: "Kettle Run" },
    carbonBend: { name: "Carbon Bend" },
    moebiusStrip: { name: "Moebius Strip" },
    blueSector: { name: "Blue Sector" },
    alloyRing: { name: "Alloy Ring" },
    twistedCanyon: { name: "Twisted Canyon" },
    greenTroll: { name: "Green Troll" },
    desertBridge: { name: "Desert Bridge" },
    templeStraight: { name: "Temple Straight" },
    goldenMarsh: { name: "Golden Marsh" },
    harborPrincipality: { name: "Harbor Principality" },
    lunarLimbo: { name: "Lunar Limbo" },
    serpentCrossing: { name: "Serpent Crossing" },
    ardennesRidge: { name: "Ardennes Ridge" },
    pretzelArena: { name: "Pretzel Arena" },
    albertGardens: { name: "Albert Gardens" },
    jumpingJack: { name: "Jumping Jack" },
    caspianBoulevard: { name: "Caspian Boulevard" },
    velvetWombat: { name: "Velvet Wombat" },
    cobaltRun: { name: "Cobalt Run" },
    blackstoneRun: { name: "Blackstone Run" },
    pebblePass: { name: "Pebble Pass" },
    zenithRun: { name: "Zenith Run" },
    speedAltar: { name: "Speed Altar" },
    titanTown: { name: "Titan Town" },
    groundControl: { name: "Ground Control" },
    crystalineHarbor: { name: "Crystaline Harbor" },
    ironHook: { name: "Iron Hook" },
    greatBazaar: { name: "Great Bazaar" },
    circuitPromax: { name: "Circuit ProMax" },
    mistfallCircuit: { name: "Mistfall Circuit" },
    stretchingCat: { name: "Stretching Cat" },
    turboShell: { name: "Turbo Shell" },
    redLagoon: { name: "Red Lagoon" },
    copperVale: { name: "Copper Vale" },
    obsidianRidge: { name: "Obsidian Ridge" },
    auroraRing: { name: "Aurora Ring" },
    furiousFast: { name: "Furious Fast" },
    lanternPier: { name: "Lantern Pier" },
    quartzHollow: { name: "Quartz Hollow" },
    needleChicane: { name: "Needle Chicane" },
    cinderSpine: { name: "Cinder Spine" },
    glassSerpent: { name: "Glass Serpent" },
    numberZero: { name: "Number Zero" },
    numberOne: { name: "Number One" },
    numberTwo: { name: "Number Two" },
    numberThree: { name: "Number Three" },
    numberFour: { name: "Number Four" },
    numberFive: { name: "Number Five" },
    numberSix: { name: "Number Six" },
    numberSeven: { name: "Number Seven" },
    numberEight: { name: "Number Eight" },
    numberNine: { name: "Number Nine" },
};

export const TRACK_SCHEDULE_KEYS = [
    'circuit',
    'sunlitTemple',
    'royalPlateau',
    'mistwoodSerpent',
    'harborParkLoop',
    'jadeSpiralCircuit',
    'cedarRidgeCircuit',
    'twinRise',
    'sakuraWeave',
    'kettleRun',
    'carbonBend',
    'moebiusStrip',
    'blueSector',
    'alloyRing',
    'twistedCanyon',
    'greenTroll',
    'desertBridge',
    'templeStraight',
    'goldenMarsh',
    'harborPrincipality',
    'lunarLimbo',
    'serpentCrossing',
    'ardennesRidge',
    'pretzelArena',
    'albertGardens',
    'jumpingJack',
    'caspianBoulevard',
    'velvetWombat',
    'cobaltRun',
    'blackstoneRun',
    'pebblePass',
    'zenithRun',
    'speedAltar',
    'titanTown',
    'groundControl',
    'crystalineHarbor',
    'ironHook',
    'greatBazaar',
    'circuitPromax',
    'mistfallCircuit',
    'stretchingCat',
    'turboShell',
    'redLagoon',
    'copperVale',
    'obsidianRidge',
    'auroraRing',
    'furiousFast',
    'lanternPier',
    'quartzHollow',
    'needleChicane',
    'cinderSpine',
    'glassSerpent',
];

export const DEFAULT_TRACK_KEY = 'circuit';

export function hasTrack(trackKey) {
    return Object.prototype.hasOwnProperty.call(TRACK_CATALOG, trackKey);
}

export function getTrackName(trackKey, fallback = 'Unknown Track') {
    return hasTrack(trackKey) ? TRACK_CATALOG[trackKey].name : fallback;
}
