export const TRACK_CATALOG = {
    circuit: { name: "Classic Circuit" },
    sunlitTemple: { name: "Sunlit Temple" },
    royalPlateau: { name: "Royal Plateau" },
    mistwoodSerpent: { name: "Mistwood Serpent" },
    harborParkLoop: { name: "Harbor Park" },
    jadeSpiralCircuit: { name: "Jade Spiral" },
    cedarRidgeCircuit: { name: "Cedar Ridge" },
    twinRise: { name: "Twin Rise" },
    sakuraWeave: { name: "Sakura Weave" },
    kettleRun: { name: "Kettle Run" },
    carbonBend: { name: "Carbon Bend" },
    moebiusStrip: { name: "Moebius Strip" },
    blueSector: { name: "Blue Sector" },
    alloyRing: { name: "Alloy Ring" },
    twistedCanyon: { name: "Twisted Canyon" },
    greenTroll: { name: "Green Troll" },
    desertBridge: { name: "Desert Bridge" },
    templeStraight: { name: "Temple Straight" },
    goldenMarsh: { name: "Golden Marsh" },
    harborPrincipality: { name: "Harbor Principality" },
    serpentCrossing: { name: "Serpent Crossing" },
    ardennesRidge: { name: "Ardennes Ridge" },
    pretzelArena: { name: "Pretzel Arena" },
    albertGardens: { name: "Albert Gardens" },
    jumpingJack: { name: "Jumping Jack" },
    caspianBoulevard: { name: "Caspian Boulevard" },
    velvetWombat: { name: "Velvet Wombat" },
    cobaltRun: { name: "Cobalt Run" },
    pebblePass: { name: "Pebble Pass" },
    zenithRun: { name: "Zenith Run" },
    speedAltar: { name: "Speed Altar" },
    groundControl: { name: "Ground Control" },
    crystalineHarbor: { name: "Crystaline Harbor" },
    ironHook: { name: "Iron Hook" },
    greatBazaar: { name: "Great Bazaar" },
    circuitPromax: { name: "Circuit ProMax" },
    stretchingCat: { name: "Stretching Cat" },
    turboShell: { name: "Turbo Shell" },
    redLagoon: { name: "Red Lagoon" },
    copperVale: { name: "Copper Vale" },
    obsidianRidge: { name: "Obsidian Ridge" },
    auroraRing: { name: "Aurora Ring" },
    furiousFast: { name: "Furious Fast" },
    lanternPier: { name: "Lantern Pier" },
    quartzHollow: { name: "Quartz Hollow" },
    needleChicane: { name: "Needle Chicane" },
    cinderSpine: { name: "Cinder Spine" },
    glassSerpent: { name: "Glass Serpent" },
    numberZero: { name: "Number Zero" },
    numberOne: { name: "Number One" },
    numberTwo: { name: "Number Two" },
    numberThree: { name: "Number Three" },
    numberFour: { name: "Number Four" },
    numberFive: { name: "Number Five" },
    numberSix: { name: "Number Six" },
    numberSeven: { name: "Number Seven" },
    mistfallCircuit: { name: "Mistfall Circuit" },
    numberEight: { name: "Number Eight" },
    numberNine: { name: "Number Nine" },
    analogAudio: { name: "Analog Audio" },
    sundayMarket: { name: "Sunday Market" },
    hardHitter: { name: "Hard Hitter" },
    roadRage: { name: "Road Rage" },
    yellowYard: { name: "Yellow Yard" },
    lunarLimbo: { name: "Lunar Limbo" },
    blackstoneRun: { name: "Blackstone Run" },
    titanTown: { name: "Titan Town" },
    eulersNumber: { name: "Euler's Number" },
    imaginaryNumber: { name: "Imaginary Number" },
    infinitePie: { name: "Infinite Pie" },
    centralDrop: { name: "Central Drop" },
    goldenRatio: { name: "Golden Ratio" },
    fedoraHat: { name: "Fedora Hat" },
    infinityIsle: { name: "Inifinity Isle" },
    kangarooKyle: { name: "Kangaroo Kyle" },
    quarterlyQuestion: { name: "Quarterly Question" },
    romanianRhapsody: { name: "Romanian Rhapsody" },
    fairyLand: { name: "Fairy Land" },
    felineFace: { name: "Feline Face" },
    darkMatter: { name: "Dark Matter" },
    appleStrudel: { name: "Apple Strudel" },
    heavyMetal: { name: "Heavy Metal" },
    knifesEdge: { name: "Knife's Edge" },
    pocketRun: { name: "Pocket Run" },
    crossCurrent: { name: "Cross Current" },
    squareDeal: { name: "Square Deal" },
    doubleHook: { name: "Double Hook" },
    doubleCrest: { name: "Double Crest" },
    heartsQueen: { name: "Queen of Hearts" },
    aceSpades: { name: "Ace of Spades" },
    twistedLadder: { name: "Twisted Ladder" },
    hairpinHook: { name: "Hairpin Hook" },
    dragonLoop: { name: "Dragon Loop" },
    thorsHammer: { name: "Thor's Hammer" },
    questionMark: { name: "Question Mark" },
    nestedRun: { name: "Nested Run" },
    mountainPeak: { name: "Mountain Peak" },
    sharkFin: { name: "Shark Fin" },
    twistedClover: { name: "Twisted Clover" },
    hookLoop: { name: "Hook Loop" },
    crookedArrow: { name: "Crooked Arrow" },
    windingRoad: { name: "Winding Road" },
    waterPistol: { name: "Water Pistol" },
    lightningHook: { name: "Lightning Hook" },
    doubleTrouble: { name: "Double Trouble" },
    brokenWing: { name: "Broken Wing" },
    twinWings: { name: "Twin Wings" },
    squareRoot: { name: "Square Root" },
    halfLife: { name: "Half Life" },
    splitJaw: { name: "Split Jaw" },
    chelseaBoots: { name: "Chelsea Boots" },
    stoneGate: { name: "Stone Gate" },
    crakowBoot: { name: "Crakow Boot" },
    slingshotRun: { name: "Slingshot Run" },
    brokenAntler: { name: "Broken Antler" },
    mantisBend: { name: "Mantis Bend" },
    cloverLeaf: { name: "Clover Leaf" },
    safariCircuit: { name: "Safari Circuit" },
    monkeyWrench: { name: "Monkey Wrench" },
    ovenMitt: { name: "Oven Mitt" },
    monkeyTail: { name: "Monkey Tail" },
    bottleOpener: { name: "Bottle Opener" },
    serpentHead: { name: "Serpent Head" },
    bullShield: { name: "Bull Shield" },
    battleHook: { name: "Battle Hook" },
    thunderCat: { name: "Thunder Cat" },
    slateCircuit: { name: "Slate Circuit" },
    blackWater: { name: "Black Water" },
    ravenRock: { name: "Raven Rock" },
    sharkBite: { name: "Shark Bite" },
    puzzlePiece: { name: "Puzzle Piece" },
    castleWall: { name: "Castle Wall" },
    blasterLoop: { name: "Blaster Loop" },
    canyonFold: { name: "Canyon Fold" },
    whistleRidge: { name: "Whistle Ridge" },
    monoRail: { name: "Mono Rail" },
    anchorPark: { name: "Anchor Park" },
    puppetMaster: { name: "Puppet Master" },
    sunsetTerrace: { name: "Sunset Terrace" },
    anvilCircuit: { name: "Anvil Circuit" },
    countryRoad: { name: "Country Road" },
    snowCircuit: { name: "Snow Circuit" },
    gripCircuit: { name: "Grip Circuit" },
    middleWay: { name: "Middle Way" },
    waterCircuit: { name: "Water Circuit" },
    spaceCircuit: { name: "Space Circuit" },
    forestTrail: { name: "Forest Trail" },
    hillsideScramble: { name: "Hillside Scramble" },
    dirtLoop: { name: "Dirt Loop" },
    ridgeRunner: { name: "Ridge Runner" },
    brokenRoad: { name: "Broken Road" },
    roughCut: { name: "Rough Cut" },
    dirtSnake: { name: "Dirt Snake" },
    wildCrest: { name: "Wild Crest" },
    dirtValley: { name: "Dirt Valley" },
    warpedLoop: { name: "Warped Loop" },
    oldMountain: { name: "Old Mountain" },
};

export const TRACK_SCHEDULE_KEYS = [
    'circuit',
    'sunlitTemple',
    'royalPlateau',
    'mistwoodSerpent',
    'harborParkLoop',
    'jadeSpiralCircuit',
    'cedarRidgeCircuit',
    'twinRise',
    'sakuraWeave',
    'kettleRun',
    'carbonBend',
    'moebiusStrip',
    'blueSector',
    'alloyRing',
    'twistedCanyon',
    'greenTroll',
    'desertBridge',
    'templeStraight',
    'goldenMarsh',
    'harborPrincipality',
    'serpentCrossing',
    'ardennesRidge',
    'pretzelArena',
    'albertGardens',
    'jumpingJack',
    'caspianBoulevard',
    'velvetWombat',
    'cobaltRun',
    'pebblePass',
    'zenithRun',
    'speedAltar',
    'groundControl',
    'crystalineHarbor',
    'ironHook',
    'greatBazaar',
    'circuitPromax',
    'stretchingCat',
    'turboShell',
    'redLagoon',
    'copperVale',
    'obsidianRidge',
    'auroraRing',
    'furiousFast',
    'lanternPier',
    'quartzHollow',
    'needleChicane',
    'cinderSpine',
    'glassSerpent',
    'lunarLimbo',
    'mistfallCircuit',
    'analogAudio',
    'hardHitter',
    'roadRage',
    'yellowYard',
    'sundayMarket',
    'blackstoneRun',
    'titanTown',
    'centralDrop',
    'fedoraHat',
    'infinityIsle',
    'kangarooKyle',
    'quarterlyQuestion',
    'romanianRhapsody',
    'fairyLand',
    'felineFace',
    'darkMatter',
    'appleStrudel',
    'heavyMetal',
    'knifesEdge',
    'pocketRun',
    'crossCurrent',
    'squareDeal',
    'doubleHook',
    'doubleCrest',
    'heartsQueen',
    'aceSpades',
    'twistedLadder',
    'hairpinHook',
    'dragonLoop',
    'thorsHammer',
    'questionMark',
    'nestedRun',
    'mountainPeak',
    'sharkFin',
    'twistedClover',
    'hookLoop',
    'crookedArrow',
    'windingRoad',
    'waterPistol',
    'lightningHook',
    'doubleTrouble',
    'brokenWing',
    'twinWings',
    'splitJaw',
    'chelseaBoots',
    'stoneGate',
    'crakowBoot',
    'slingshotRun',
    'brokenAntler',
    'mantisBend',
    'cloverLeaf',
    'safariCircuit',
    'monkeyWrench',
    'ovenMitt',
    'monkeyTail',
    'bottleOpener',
    'serpentHead',
    'bullShield',
    'battleHook',
    'thunderCat',
    'slateCircuit',
    'blackWater',
    'ravenRock',
    'sharkBite',
    'puzzlePiece',
    'castleWall',
    'blasterLoop',
    'canyonFold',
    'whistleRidge',
    'monoRail',
    'anchorPark',
    'puppetMaster',
    'sunsetTerrace',
    'anvilCircuit',
    'waterCircuit',
    'spaceCircuit',
    'warpedLoop',
];

export const DEFAULT_TRACK_KEY = 'circuit';

export function hasTrack(trackKey) {
    return Object.prototype.hasOwnProperty.call(TRACK_CATALOG, trackKey);
}

export function getTrackName(trackKey, fallback = 'Unknown Track') {
    return hasTrack(trackKey) ? TRACK_CATALOG[trackKey].name : fallback;
}
