export default {
    testRunner: 'vitest',
    packageManager: 'npm',
    coverageAnalysis: 'perTest',
    ignoreStatic: true,
    reporters: ['progress', 'clear-text', 'html'],
    thresholds: {
        high: 80,
        low: 60,
        break: null
    },
    vitest: {
        configFile: 'vitest.config.js',
        related: true
    },
    mutate: [
        'game/race/run-policy.js',
        'game/race/result-flow.js',
        'game/race/ring-buffer.js',
        'game/race/simulation.js',
        'game/race/replay.js',
        'game/track/runtime.js',
        'game/car/handling.js',
        'game/daily-challenge/storage.js',
        'game/daily-challenge/service.js',
        'game/player/progress-state.js',
        'game/scoreboard/service.js',
        'game/scoreboard/verification-queue.js',
        'game/scoreboard/snapshot.js',
        'game/shared/checkpoint-times.js',

        'game/shared/leaderboard-identity.js',
        'game/shared/values.js',
        'game/shared/pb-ghost-format.js',
        'game/shared/pb-ghost-recorder.js',
        'game/shared/reddit-avatar.js',
        'game/shared/utc-day.js',
        'game/shared/race-time-text.js',

        'src/server/daily/daily-gp-store.ts',
        'src/server/competition/replay-validator.ts',
        'src/server/player/player-token.ts',
        'src/server/request/request-rate-limit-identity.ts',
        'src/server/competition/pb-ghost-trace.ts',
        'src/server/daily/daily-gp-model.ts',
        'src/server/daily/daily-gp-share.ts',
        'src/server/competition/pb-ghost-store.ts',
        'src/server/posts/post-bound-challenge.ts',
        'src/server/moderator/moderator-access.ts',

        'src/server/redis/redis-lock.ts',
        'src/server/shared/value-guards.ts',
        'src/server/shared/format-race-time.ts',
        'src/server/redis/redis-names.ts',
        'src/server/request/rate-limit.ts',
        'src/server/redis/redis-lock-retry.ts',
        'src/server/guest-transfer/progress-transfer-reply.ts',
        'src/server/redis/redis-compressed-value.ts',
        'src/server/daily/daily-gp-post-store.ts',
        'src/server/podium/daily-podium-post-store.ts',
        'src/server/podium/daily-podium-service.ts',
        'src/server/daily/daily-post-service.ts',
        'src/server/daily/daily-autopost-store.ts',
        'src/server/podium/daily-podium-autopost-store.ts',
        'src/server/posts/autopost-subscription-store.ts',
        'src/server/daily/daily-gp-history-backfill.ts'
    ],
    ignorePatterns: [
        '.cursor',
        '.venv',
        'analyses/**',
        'docs/**',
        'downloaded tracks/**',
        'site/**',

        '*.css',
        '*.html',
        '*.png',
        '*.csv'
    ]
};
